# Generated by Django 5.0.6 on 2025-06-11 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_department_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='departmenttranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Department Translation'},
        ),
    ]
