# Generated by Django 5.0.6 on 2025-06-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_department_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='img',
            new_name='img1',
        ),
        migrations.AddField(
            model_name='department',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='Department/'),
        ),
        migrations.AddField(
            model_name='department',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='Department/'),
        ),
    ]
