# Generated by Django 5.0.6 on 2025-06-26 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_rename_img_department_img1_department_img2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='img1',
            new_name='img',
        ),
    ]
