# Generated by Django 5.0.6 on 2025-06-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_rename_img1_department_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='img2',
            new_name='img1',
        ),
        migrations.RemoveField(
            model_name='department',
            name='img3',
        ),
    ]
