# Generated by Django 5.0.6 on 2025-06-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_remove_department_img1'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='Department/'),
        ),
    ]
